apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klessen-cloud
spec:
  dnsNames:
  - klessen.cloud
  - '*.klessen.cloud'
  issuerRef:
    name: letsencrypt-staging
  secretName: klessen-cloud-tls
