apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-operator
resources:
  - ../../base/rabbitmq-cluster-operator
  - release.yaml
configMapGenerator:
- name: values
  files:
  - values.yaml
