apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- minio.ns.yaml
- ns-admin.rbac.yaml
- tenant.yaml
- tenant-minio-creds-secret_deprecated.yaml
secretGenerator:
- files:
  - secret/ca/vault-ca.crt
  name: vault-ca-cert
  namespace: minio
generatorOptions:
  disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    owner: platform-tooling
patches:
- path: tenant.kes.yaml
- path: tenant.pools.yaml
- path: tenant.prometheus.yaml
## - path: tenant.log.yaml
