apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: minio
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: tilo@klessen.cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
