---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-bootstrap
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
  - apiGroups: [""]
    resources:
    - "secrets"
    verbs:
    - "create"
    - "update"
    - "get"
    - "patch"
