apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - vault.ns.yaml
  - ns-admin.rbac.yaml
  - cronjob.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
commonLabels:
  owner: platform-tooling
configMapGenerator:
  - name: vault-bootstrap
    files:
    - vault-bootstrap.sh
secretGenerator:
  - name: tls-ca
    files:
    - ./secret/ca/tls.crt
    - ./secret/ca/tls.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
