apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 24h
  releaseName: vault
  targetNamespace: vault
  chart:
    spec:
      chart: vault
      version: '0.21.0'
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
      interval: 24h
  valuesFrom:
    - kind: ConfigMap
      name: values
