---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-connectivity-check
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./entity/platform-engineering/staging/external-connectivity-check
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 2m
