apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-operator.ns.yaml
  - release.yaml
commonLabels:
  owner: platform-tooling
configurations:
  - kustomizeconfig.yaml
