apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 24h
  releaseName: minio-operator
  targetNamespace: minio-operator
  chart:
    spec:
      chart: operator
      version: 'v4.5.2'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 24h
  valuesFrom:
    - kind: ConfigMap
      name: values
