apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    ingress.cilium.io/loadbalancer-mode: "dedicated"
    io.cilium/lb-ipam-ips: "192.168.123.200"
spec:
  ingressClassName: cilium
  rules:
  - host: echoserver.vmware.klessen.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 80
  tls:
    - hosts:
      - echoserver.vmware.klessen.cloud
      secretName: echoserver-tls
