apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echoserver
  namespace: echoserver
spec:
  dnsNames:
  - echoserver.vmware.klessen.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: echoserver-tls
