apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- release.yaml
commonLabels:
  owner: platform-tooling
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: values
  files:
  - values.yaml