apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: ww-tf-controller
  interval: 1h0m0s
  valuesFrom:
  - kind: ConfigMap
    name: values
