apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echoserver
resources:
  - ../../base/echoserver
  - echoserver.ing.yaml
  - echoserver.cert.yaml
  - echoserver.ippool.yaml
commonLabels:
  owner: platform-tooling
