apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: examplednsrecord
  namespace: kube-system
spec:
  endpoints:
  - dnsName: unf-01.backend.klessen.cloud
    recordTTL: 180
    recordType: A
    targets:
    - 192.168.23.3
    # Provider specific configurations are set like an annotation would on other sources
    providerSpecific: {}
    #- name: external-dns.alpha.kubernetes.io/cloudflare-proxied
    #  value: "true"