apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-pihole-2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-pihole-2
  template:
    metadata:
      labels:
        app: external-dns-pihole-2
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns-pihole-2
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        # If authentication is disabled and/or you didn't create
        # a secret, you can remove this block.
        env:
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: api-token
              name: pihole-2-credentials
        - name: EXTERNAL_DNS_PIHOLE_SERVER
          valueFrom:
            configMapKeyRef:
              key: server
              name: pihole-2-connection
        args:
        - --source=crd
        - --source=node
        # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
        # You don't need to set this flag, but if you leave it unset, you will receive warning
        # logs when ExternalDNS attempts to create TXT records.
        - --registry=noop
        # IMPORTANT: If you have records that you manage manually in Pi-hole, set
        # the policy to upsert-only so they do not get deleted.
        - --policy=upsert-only
        - --provider=pihole
        - --log-level=debug
        # Change this to the actual address of your Pi-hole web server
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files