apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-gandi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-gandi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-gandi
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        args:
        - --source=service
        #- --domain-filter=example.com # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=gandi
        env:
        - name: GANDI_KEY
          valueFrom:
            secretKeyRef:
              key: api-token
              name: gandi-credentials