apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - external-dns-gandi.dp.yaml
  - external-dns-pdns.dp.yaml
  - external-dns.sa.yaml
  - external-dns.cr.yaml
  - external-dns.crb.yaml
commonLabels:
  owner: platform-tooling
