apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - external-dns-gandi.dp.yaml
  - external-dns-pdns.dp.yaml
  - external-dns-pihole-1.dp.yaml
  - external-dns-pihole-2.dp.yaml
  - example-pihole.dnsep.yaml
  - ../../base/external-dns
commonLabels:
  owner: platform-tooling
configMapGenerator:
  - name: pdns-connection
    literals:
    - server=http://10.255.250.252
  - name: pihole-1-connection
    literals:
    - server=http://192.168.23.3
  - name: pihole-2-connection
    literals:
    - server=http://192.168.23.33/admin
