apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - external-dns-gandi.dp.yaml
  - external-dns-pdns.dp.yaml
  - ../../base/external-dns
commonLabels:
  owner: platform-tooling
configMapGenerator:
  - name: pdns-connection
    literals:
    - server=http://10.255.250.252
