apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.ns.yaml
namespace: cert-manager
commonLabels:
  owner: platform-tooling
configurations:
  - kustomizeconfig.yaml
