---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-webhook-gandi
  namespace: flux-system
spec:
  suspend: false
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./entity/platform-tooling/vmware/cert-manager-webhook-gandi
  prune: true
  wait: true
  timeout: 3m
  dependsOn:
  - name: cert-manager
