---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  suspend: false
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./entity/platform-tooling/vmware/cert-manager
  prune: true
  wait: true
  timeout: 3m
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-cainjector
    namespace: cert-manager
  - apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager

