---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoserver
  namespace: flux-system
spec:
  suspend: false
  interval: 5m0s
  dependsOn:
  - name: cert-manager-webhook-gandi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./entity/platform-tooling/vmware/echoserver
  prune: true
  wait: true
  timeout: 3m
