---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: eck-operator
  namespace: flux-system
spec:
  suspend: true
  interval: 5m0s
  path: ./entity/platform-tooling/vmware/eck-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: StatefulSet
    name: eck-operator
    namespace: elastic-system
  timeout: 5m
