---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubegres
  namespace: flux-system
spec:
  suspend: true
  interval: 5m0s
  path: ./entity/platform-tooling/local/kubegres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kubegres-controller-manager
    namespace: kubegres-system
  timeout: 5m