---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-terraform
  namespace: flux-system
spec:
  suspend: true
  interval: 5m0s
  path: ./entity/platform-tooling/vmware/vault-terraform
  prune: true
  wait: true
  timeout: 3m
  dependsOn:
  - name: vault
  - name: ww-tf-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
