apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 72h
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 'v1.13.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: values
