apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/eck-operator
namespace: elastic-system
commonLabels:
  owner: platform-engineering
configMapGenerator:
  - name: values
    files:
      - values.yaml
