---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-operator-all-in-one
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./entity/platform-engineering/local/elastic-operator-all-in-one-manifest
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: StatefulSet
    name: elastic-operator
    namespace: elastic-system
