---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: log-es-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./entity/platform-tooling/local/log-es-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: log-es-cluster
      namespace: log
  timeout: 5m
