---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./entity/platform-tooling/local/minio
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: minio-operator
  #  - name: bootstrap-ns-minio
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: minio.min.io/v2
      kind: Tenant
      name: minio
      namespace: minio
    - apiVersion: apps/v1
      kind: StatefulSet
      name: minio-kes
      namespace: minio
    - apiVersion: apps/v1
      kind: StatefulSet
      name: minio-pool-0
      namespace: minio
