---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-terraform
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./entity/platform-tooling/local/vault-terraform
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
