apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
spec:
  interval: 72h
  releaseName: rabbitmq-cluster-operator
  targetNamespace: rabbitmq-operator
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: '3.2.0'
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-cluster-operator
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: values
