apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8ssandra-operator-v1.8.1.yaml
namespace: k8ssandra-operator
commonLabels:
  app: k8ssandra-operator
  owner: platform-tooling
configurations:
  - kustomizeconfig.yaml
