apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
resources:
  - ../../base/minio-operator
commonLabels:
  owner: platform-tooling
patchesStrategicMerge:
  - release-patch.yaml
configMapGenerator:
  - name: values
    files:
      - values.yaml
