apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/k8ssandra-operator
  - release.yaml
namespace: k8ssandra-operator
commonLabels:
  app: k8ssandra-operator
  owner: platform-tooling
configMapGenerator:
  - name: values
    files:
      - values.yaml
