apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      securityContext:
        fsGroup: 1100
      initContainers:
        - name: graylog-cacerts
          volumeMounts:
            - name: graylog-es-ca-cert
              mountPath: /etc/ssl/certs/graylog-es-ca-cert.pem
              subPath: graylog-es-ca-cert.pem
              readOnly: false
            - name: graylog-keystore
              mountPath: /keystore
              readOnly: false
      containers:
        - name: mongodb
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: graylog-mongodb
              mountPath: /data/db
        - name: graylog
          ports:
            - name: web
              containerPort: 9000
            - name: api
              containerPort: 12900
            - name: gelf
              containerPort: 12201
              protocol: UDP
            - name: gelftcp
              containerPort: 12201
            - name: syslog
              protocol: UDP
              containerPort: 12591
          env:
            - name: AUTO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GRAYLOG_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: graylog
                  key: password.secret
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
            - name: GRAYLOG_ROTATION_STRATEGY
              value: "time"
            - name: GRAYLOG_RETENTION_STRATEGY
              value: "delete"
            - name: GRAYLOG_ELASTICSEARCH_CLUSTER_NAME
              value: graylog
            - name: GRAYLOG_MONGODB_URI
              value: "mongodb://127.0.0.1:27017/graylog"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              valueFrom:
                secretKeyRef:
                  name: graylog
                  key: svc.elastic
            - name: GRAYLOG_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graylog
                  key: password.graylog-user
            - name: GRAYLOG_ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: log-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: graylog-journal
              mountPath: /usr/share/graylog/data/journal
            - name: graylog-plugins
              mountPath: /usr/share/graylog/plugin
            - name: graylog-es-ca-cert
              mountPath: /etc/ssl/certs/graylog-es-ca-cert.pem
              subPath: graylog-es-ca-cert.pem
              readOnly: false
            - name: graylog-keystore
              mountPath: /keystore
              readOnly: true
      volumes:
        - name: graylog-keystore
          emptyDir: {}
        - name: graylog-es-ca-cert
          secret:
            secretName: log-es-http-ca-internal
            items:
              - key: tls.crt
                path: graylog-es-ca-cert.pem
        - name: graylog-journal
          persistentVolumeClaim:
            claimName: graylog-journal
        - name: graylog-plugins
          persistentVolumeClaim:
            claimName: graylog-plugins
        - name: graylog-mongodb
          persistentVolumeClaim:
            claimName: graylog-mongodb
