apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-connectivity-check
spec:
  selector:
    matchLabels:
      app: external-connectivity-check
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-connectivity-check
    spec:
      containers:
      - image: registry.gitlab.com/swinkelhofer/http-echo-service:0.0.2
        name: http-echo-service
        ports:
        - containerPort: 5000
          name: web
