apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-operator
resources:
  - rabbitmq.ns.yaml
commonLabels:
  owner: platform-tooling
  app: rabbitmq-cluster-operator
configurations:
  - kustomizeconfig.yaml
