apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klessen-cloud
spec:
  dnsNames:
  - api.vmware.klessen.cloud
  - '*.vmware.klessen.cloud'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: klessen-cloud-tls
