apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-gandi
  namespace: cert-manager
spec:
  interval: 72h
  releaseName: cert-manager-webhook-gandi
  chart:
    spec:
      chart: cert-manager-webhook-gandi
      version: 'v0.2.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-gandi
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: values
