apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: academy-admin
  namespace: log
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: rico@klessen.cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
