apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-mongodb-mt17
  labels:
    academy: shared
    service: graylog
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /srv/graylog-mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mt17.prod.klessen.cloud
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
