apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - backup.cronjob.yaml
  - sealedsecrets-reader.sa.yaml
  - sealedsecrets-reader.role.yaml
  - sealedsecrets-reader.rb.yaml
configMapGenerator:
- name: sealed-secrets-backup-script
  files:
    - script.py
generatorOptions:
  disableNameSuffixHash: false
commonLabels:
  owner: platform-tooling
