apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 72h
  releaseName: sealed-secrets-controller
  targetNamespace:  kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: '2.11.0'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
