apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: minio
  name: minio-console
spec:
  externalTrafficPolicy: Local
  ports:
    - name: https-console
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    v1.min.io/tenant: minio
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 172.18.0.101
