apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: minio
  name: minio-api
spec:
  externalTrafficPolicy: Local
  ports:
    - name: https-minio
      port: 443
      protocol: TCP
      targetPort: 9000
  selector:
    v1.min.io/tenant: minio
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 172.18.0.100
