apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sealed-secrets
  - release.yaml
namespace: kube-system
commonLabels:
  owner: platform-engineering
secretGenerator:
- literals:
  - secret_access_key="KKEvlR+g/2hlAPh8ZjqgPc4Qk3iOoMVJ5irzfjag"
  - secret_key_id="AKIA3SEWEEAGHKRC2ZOF"
  name: sealedsecrets-aws-credentials
patches:
- path: add_env_variables.yaml
  target:
    group: batch
    version: v1beta1
    kind: CronJob
    name: sealed-secrets-backup
